main: main.Main
version: 1.0
name: WoldviewPlugin
depend: [Vault]
commands:
  check:
    usage: /check
    aliases: publish, Confirm, reset
  test-economy:
    usage: /test-economy
    aliases: test-economy
  test-permission:
    usage: /test-permission
    aliases: test-permission